
# 実行するタスク設定
tasks:
  wp_task:
    do_make_clean: True
    do_clustering: True
    do_make_feat: True
    do_train: True
    do_predict: True
    do_predict_for_eval: True
    do_visualize: True
  opt_task:
    do_optimize: True
    do_visualize: True

# 共通部分のパラメータ
common:
  seed: 3655
  # ディズニーランド(tdl)orディズニーシー(tds) or both
  land_type: both

  folder_name: ${common.visit_date}
  load_from: # 学習済みモデルをloadする場合は指定 

  train_start_date: "2022-4-25" # 学習開始日
  predict_date: "2023-09-20" # 予測実施日
  visit_date: "2023-09-21" #来園予定日
  visit_time: "09:00" #来園時刻
  return_time: "20:30" #退園時刻

  is_only_predict: False # 予測のみを行うかどうか
  is_train_predict: False # 学習データに対する予測を行うか 
  is_valid_predict: False # 評価データに対する予測を行うか 
  
  cpu_level: "high" #["high" "middle" "low"]
  cpu_core: 



# 入力ファイル
input: 
  input_dir: ./data
  # raw data の場所
  path_waittime_dir: ${input.input_dir}/${common.land_type}/wait_time
  path_weather_dir: ${input.input_dir}/weather
  path_distance_file: ${input.input_dir}/${common.land_type}/distance.csv
  path_master_file: disney_route_optimize/config/park_master/${common.land_type}/park_master.csv
  path_rank_file: disney_route_optimize/config/park_master/${common.land_type}/rank.csv

# 出力ファイル
output:
  output_dir: ./result
  wp_output:
    path_wp_dir: ${output.output_dir}/wp_result
    path_preprocessed_dir: ${output.wp_output.path_wp_dir}/preprocessed
    path_features_dir: ${output.wp_output.path_wp_dir}/feature
    path_train_dir: ${output.wp_output.path_wp_dir}/train
    path_clustering_dir: ${output.wp_output.path_wp_dir}/clustering
    path_predict_dir: ${output.wp_output.path_wp_dir}/predict
    path_visualize_dir: ${output.wp_output.path_wp_dir}/visualize

    weather_file: ${output.wp_output.path_preprocessed_dir}/weather.csv
    waittime_file: ${output.wp_output.path_preprocessed_dir}/waititme.csv
    features_file: ${output.wp_output.path_features_dir}/features.csv
    features_test_file: ${output.wp_output.path_features_dir}/features_test.csv
    path_model: ${output.wp_output.path_train_dir}/model.pickle
    cat_report_train_file: classification_train_report.csv
    cat_report_valid_file: classification_valid_report.csv
    pred_train_file: train_pred.csv
    pred_valid_file: valid_pred.csv
    pred_test_file: result_pred.csv

    path_clustering_model: ${output.wp_output.path_clustering_dir}/cluster.json 
    path_clustering_dict: ${output.wp_output.path_clustering_dir}/attraction2cluster.pickle 
    path_clustered_waittime: ${output.wp_output.path_clustering_dir}/clustered_waittime.csv 
    
  opt_output:
    path_opt_dir: ${output.output_dir}/opt_result
    path_input_dir: ${output.opt_output.path_opt_dir}/input
    path_first_optimize_dir: ${output.opt_output.path_opt_dir}/${common.land_type}/first_optimize
    path_second_optimize_dir: ${output.opt_output.path_opt_dir}/${common.land_type}/second_optimize
    path_regression_dir: ${output.opt_output.path_opt_dir}/regression

    path_regression_file: regression_result.csv
    path_plan_file: plan.csv
    path_time_file: time_matrix.csv
    path_location_file: location_matrix.csv

  

  

  