

opt_params:
  threads: 8
  timeLimit: 30

first_opt:
  objective: 
    objective_total_visit: False
    objective_total_popular_visit: True

  constraints:
    constraint_global_time : True
    constraint_global_mtz : True
    constraint_mtz : True
    constraint_play_time : True
    constraint_visit_once : True
    constraint_global_once : True
    constraint_time_window : True

second_opt:
  objective: 
    objective_total_visit: False
    objective_total_popular_visit: True

  constraints:
    constraint_global_time : True
    constraint_global_mtz : True
    constraint_mtz : True
    constraint_play_time : True
    constraint_visit_once : True
    constraint_global_once : True
    constraint_time_window : True

cost:
  sep_time: 15 # 予測待ち時間の刻み（分）# 15固定
  step_time: 0.7 # 1歩の時間（秒） default = 0.5
  buffer_time: 300 #1アトラクション毎のバッファ(秒)

rank:
  split_rank : 20 # 最適化段階をどこで区切るか
  

