preprocess:
  th_annomaly: 90 # 異常検知：許容差分値(分)
  max_value: 250 # 上限値の設定(分)
  min_value: 0 # 下限値の設定（分）

feature:
  recently_num: 10 # 特徴量として使う直近の値
  n_jobs : ${common.cpu_core} # 並列化する数

  # 特徴量として使うクラスタリングのパラメータ
  clustering:
    n_clusters: 6
    n_init: 100
    max_iter: 1000

valid:
  valid_days: 14 # 直近何日を評価データとするか(2週間)


predict:
  predict_day: 2 # 何日先を予測するか(データ取得の関係上2日以上を指定する必要)


# kshapeのパラメータ
clustering:
    n_clusters: 4
    kshape:
      verbose : True
      n_init: 50
      max_iter: 1000



# lightgbmのパラメータ
wp_model:
    regression_params:
      custom_metrics: rmsle
      params:
        task: 'train'
        boosting_type: 'gbdt'
        metric: 'mae' 
        learning_rate: 0.001
        num_iterations: 50000
        num_leaves: 128
        max_depth: -1
        min_data_in_leaf: 500
        reg_alpha: 0.3
        reg_lambda: 0.3
        bagging_fraction: 0.9
        bagging_freq: 1
        min_gain_to_split: 0.0
        n_jobs: ${common.cpu_core}
        verbosity: -1
      early_stopping_rounds: 300
      log_eval: 10





